[[collection]]
type = "card"
date = "Jun 07, 2026"
title = "Curiosity #1"
content = "Curiosity is never sated. It makes you chase adjacencies. Adjacencies open you to new subjects. It is a positive feedback loop. But unlike most, a good one!"

[[collection]]
type = "card"
date = "Jan 05, 2026"
title = "Familiarity #1"
content = "Familiarity hides flaws. It chisels away at the annoyances until what remains is the underlying perfection."
