[[collection]]
type = "card"
date = "Mar 29, 2025"
title = "Epic"
content = "The greatest epics that our culture venerates teaches us that good always trumps over evil.... And that joint families do not get along. Ever."